### ISSUE TITLE
Raspberry Pi Images were removed

### ISSUE THREAD

**Issue by lucasoskorep** [endeavouros-arm/images#3]
As title says - raspberry pi images were removes and all  versions of the installer fail to work as a result

**Comment by killajoe** [comment]
yes as far as i know they work on uploading new ones currently not easy to handle ARM on arch sadly..

**Comment by endeavouros-arm** [comment]
We had a major make over with Calamares which broke all the images, thus they were re-moved.
I have just uploaded the following images with the tags as follows
ddimg-rpi-20231124 
ddimg-odroid-n2-20231124
ddimg-radxa-5B-20231124
These are CLI command dd compatible and can be installed on a target storage device using dd, rpi-imager, gnome-disk-utility, or any other compatible "burner" program.
In endeavouros-arm/images just select the architecture appropriate image, and download the two files.
Go to the folder the files downloaded to and verify with the sha512sum file.
sha512sum -c filename.sha512sum
Then burn to a target uSD, eMMC, or USB SSD.

Tomorrow I will start getting the rootfs images script  working and create new rootfs images and get the rootfs installer going.

**Comment by lucasoskorep** [comment]
@endeavouros-arm amazing - thank you! 

On a side note - was looking through docs on how to start trying to build an image from the github repos but it does not look immediately possible.  Are there any docs on how to get started contributing to endeavorOS-arm?

**Comment by endeavouros-arm** [comment]
I'm always looking for help.  I didn't find lucasoskorep in the EndeavourOS forum, so go to forum.endeavouros.com
and create an account.  I am pudge on the EnOS forum, send me a PM (Private Message) and we can start from there.

Instructions are rather lengthy for here, PM me and I will go into how to do it.  Then after you experiment with it, maybe the first thing you can do to contribute is write up an article on how to create an EnOS ARM image for the WiKi

If it is OK with you, I will close this issue.  Let me know when you receive this comment.

Pudge
