### ISSUE TITLE
Missing image enosARM-server-rpi-latest.tar.zst in the URL

### ISSUE THREAD

**Issue by vochong** [endeavouros-arm/images#4]
sudo ./ARM-install-server-image.sh

Partitioning, & formatting storage device...
Partition 3 does not start on physical sector boundary.

Partitioning storage device /dev/sdb...

partition name = /dev/sdb

Formatting storage device /dev/sdb...

If "/dev/sdx contains an existing file system Labelled XXXX" or similar appears, Enter: y

mkfs.fat 4.2 (2021-01-31)
mke2fs 1.47.0 (5-Feb-2023)
/dev/sdb2 contains a ext4 file system labelled 'ROOT'
	last mounted on Sat Feb 10 10:49:05 2024
Creating filesystem with 7739648 4k blocks and 1937712 inodes
Filesystem UUID: adaf7848-dd02-4836-a240-74eecb3f3b85
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done   

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59317    0 59317    0     0   161k      0 --:--:-- --:--:-- --:--:--  161k

Downloading image enosARM-server-rpi-latest.tar.zst tag = 

--2024-02-10 10:50:35--  https://github.com/endeavouros-arm/images/releases/download//enosARM-server-rpi-latest.tar.zst
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-10 10:50:35 ERROR 404: Not Found.

Untarring the image...takes 4 to 5 minutes.
pv: failed to read file: enosARM-server-rpi-latest.tar.zst: No such file or directory
zstd: /*stdin*\: unexpected end of file 

syncing files...takes 4 to 5 minutes.

In /etc/fstab and /boot/cmdline.txt changing Disk labels to UUID numbers.
mv: cannot stat '/mnt/etc/fstab': No such file or directory
./ARM-install-server-image.sh: line 96: /mnt/etc/fstab: No such file or directory
./ARM-install-server-image.sh: line 97: /mnt/etc/fstab: No such file or directory
./ARM-install-server-image.sh: line 98: /mnt/etc/fstab: No such file or directory
./ARM-install-server-image.sh: line 99: /mnt/etc/fstab: No such file or directory
awk: fatal: cannot open file `/mnt/boot/cmdline.txt' for reading: No such file or directory
sed: can't read /mnt/boot/cmdline.txt: No such file or directory

Almost done! Just a couple of minutes more for the last step.

End of script!

Be sure to use a file manager to umount the device before removing the USB SD reader

The default user is alarm with the password alarm
The default root password is root

**Comment by endeavouros-arm** [comment]
enosARM-server-rpi4-latest.img.xz is missing.  I was rearranging things with the advent of RPi 5 and the server fell through the cracks.

I should have it available late today or tomorrow.

**Comment by mj-mo** [comment]
checking on this, also had this failure running the script.

**Comment by endeavouros-arm** [comment]
The latest enosARM-server-rpi4-latest.img.xz image is back in the images-release section.  It now works for both Raspberry Pi 4 AND Raspberry Pi 5.

https://github.com/endeavouros-arm/images/releases

Pudge
