### ISSUE TITLE
ddimg-rpi5-20240215 uninstallable due to issues with initial update process.

### ISSUE THREAD

**Issue by CovLinuxGuy** [endeavouros-arm/images#5]
During the install process, there are KDE packages that have dependancies that break due to the pacman -Syyu process. 
Suggest test running the install to show broken packages and the failure of the install to glean further insight.
Possible remedy is a generation of a new install image for use with newer and more current packages. 

IMAGE UNUSABLE UNTIL REFRESHED SYSTEM IS MADE AVAILABLE. 

UPDATES TO CURRENTLY INSTALLED IMAGES CAUSES BREAKS IN SYSTEM AND CAUSES CRASHES AND SYSTEM FREEZES.

**Comment by killajoe** [comment]
pacman -Syyu should not be used on regular updates, only in rare cases if you really need to refresh package also they are already up to date. 
The package dependendency issue with the change from kde 5 to 6 upstream is resolved now. 
New images with a more minimal way to install are up to download.
