### ISSUE TITLE
ddimg-rpi4-20240215 problems

### ISSUE THREAD

**Issue by robastala** [endeavouros-arm/images#6]
System : Raspberry Pi 4b
SD Card : SanDisk Ultra 32GB

Image : enosLinuxARM-rpi4-latest.img.xz (ddimg-rpi4-20240215)

Software used :
-Raspberry Pi Imager v1.7.2
-balena Etcher v1.18.11

Problems:

1)
First boot configured wifi but installer window would not work anymore. Rebooted but the image did not work. Needed to re-flashed the image. Tried this a few time but as soon the you leave the installer window it stops working.

Fixed the problem by connecting the network cable. Installer windows would work and could begin installation.

2)
Error at the end of the installation. Booting would not go to desktop. It would go to terminal. User and password would not work.

Link to error:
[http://termbin.com/hg8d](http://termbin.com/hg8d)

**Comment by killajoe** [comment]
New images should resolve such issues.
